### ISSUE TITLE
Please provide binaries for download on GitHub Releases

### ISSUE THREAD

**Issue by probonopd** [xtools-at/Electron-PWA-Wrapper#1]
https://github.com/xtools-at/Electron-PWA-Wrapper/blob/6e7e5b1ea2aad3c5f49eda09f91724f58d4e2bde/README.md#build-for-linux-any-distro-using-appimage describes how to build an AppImage. Can you please provide one on https://github.com/xtools-at/Electron-PWA-Wrapper/releases so that users don't have to build it themselves? Thanks.

**Comment by xtools-at** [comment]
What's that good for? You have to customise a lot of the code first to make it fit *your own* web app, why should there be a prebuilt release of the example app? 

There's a repo where I put the releases of the [Leasingrechnen.at](https://www.leasingrechnen.at) app:
[https://github.com/xtools-at/Leasingrechner-Releases](https://github.com/xtools-at/Leasingrechner-Releases)
But the Linux app is not ready yet, app icons are still buggy.

**Comment by probonopd** [comment]
Yes, I think it's always good to have default examples to test before one has to compile something. Thanks.

**Comment by xtools-at** [comment]
Ok, I'll add the Release repo to the README - still, I don't think that compiling is that hard here, it's literally 3 commands (git clone, npm i, npm run build), if one's working with Linux, one should be able to do that 😁

**Comment by xtools-at** [comment]
Here we go, I've added the repo to the [Release Notes of 1.1 beta](https://github.com/xtools-at/Electron-PWA-Wrapper/releases/tag/1.1-beta).

Btw, if you manage to solve the App- and Tray-Icon issue on Linux, a Pull Request would be much appreciated!

**Comment by probonopd** [comment]
Thanks @xtools-at but where exactly do I find the AppImage for download? (Am I blind?)

**Comment by xtools-at** [comment]
> But the Linux app is not ready yet, app icons are still buggy.

I didn't upload a build since it's not ready yet (see #3 ). I've dropped you my[ latest Dev-Version on Drive](https://drive.google.com/open?id=1bRxtwG1CKseYuaf0BBuvn8Dv_OyM3oTv).

**Comment by xtools-at** [comment]
just compiled a new version for testing a fix with #3 - I've updated the link and comment above.
the compiled AppImage will be added to the Releases-Repo once it's done.

**Comment by xtools-at** [comment]
Will be adding a working Linux version within the next 30min to the release-repo.
